
version: "3.8"
services:
  app:
    build: .
    container_name: new-app
    working_dir: /src
    volumes: 
      - '.:/src'
      - /app/node_modules
    restart: always
    ports:
      - 8000:8000
    stdin_open: true
    command: /bin/sh -c "yarn start"