
version: "3.8"
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: new-app
    working_dir: /src
    volumes: 
      - '.:/src'
      - /app/node_modules
    restart: always
    ports:
      - 3003:3003
    command: /bin/sh -c "yarn start"