
version: "3.7"
services:
  app:
    build: .
    container_name: new-app
    working_dir: /src
    volumes: 
      - '.:/src'
    restart: always
    ports:
      - 8080:8080
    command: /bin/sh -c "yarn start"